# Generated by Django 5.1.6 on 2025-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanesAggregatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('value', models.TextField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('range_of_values', models.BooleanField(blank=True, null=True)),
                ('mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stdev', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q3', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'nhanes_aggregated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('sex', models.TextField()),
                ('gender', models.TextField()),
                ('primary_language', models.TextField()),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('tobacco_status', models.JSONField(blank=True, default=dict)),
                ('alcohol_use', models.JSONField(blank=True, default=dict)),
                ('drug_use', models.JSONField(blank=True, default=dict)),
                ('housing', models.JSONField(blank=True, default=list)),
                ('employment', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('marital_status', models.JSONField(blank=True, default=list)),
                ('children', models.IntegerField(default=0)),
                ('pets', models.JSONField(blank=True, default=dict)),
                ('travel', models.JSONField(blank=True, default=dict)),
                ('chief_complaint', models.TextField()),
                ('diet', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'generated_patient',
            },
        ),
    ]
