# Generated by Django 5.1.6 on 2025-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedNhanesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('value', models.TextField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('range_of_values', models.BooleanField(blank=True, default=False, null=True)),
                ('mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('median', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mode', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stdev', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q3', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'nhanes_aggregated',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NhanesAggregatedData',
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.TextField(default=''),
        ),
    ]
